# Generated by Django 4.1.1 on 2023-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_stock_options_remove_size_pricemdl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ro_pl',
            new_name='name_gr_pl',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_ro_s',
            new_name='name_gr_s',
        ),
        migrations.RemoveField(
            model_name='basis',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='basis',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='name_ro',
        ),
        migrations.RemoveField(
            model_name='bedsheets',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru_pl',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru_s',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='property_ro',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='property_ru',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='desc_ro',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_ro',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='basis',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bed',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedsheets',
            name='name_gr',
            field=models.CharField(default='', max_length=32, verbose_name='Название (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blanket',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='property_gr',
            field=models.CharField(blank=True, max_length=64, verbose_name='Вариант выбора (en)'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mattresspad',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pillow',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stand',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='desc_gr',
            field=models.TextField(default='', verbose_name='Описание (en)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technology',
            name='name_gr',
            field=models.CharField(blank=True, max_length=32, verbose_name='Название (en)'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='bedsheets',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='bedsheets',
            name='name_en',
            field=models.CharField(max_length=32, verbose_name='Название (ru)'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='property_en',
            field=models.CharField(max_length=64, verbose_name='Вариант выбора (ru)'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='desc_en',
            field=models.TextField(verbose_name='Описание (ru)'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name_en',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название (ru)'),
        ),
    ]
