# Generated by Django 4.1.1 on 2023-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_alter_bedsheetssize_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Mattress', 'Mattress'), ('Pillow', 'Pillow'), ('MattressPad', 'Mattress Pad'), ('Blanket', 'Blanket'), ('Bed', 'Bed'), ('Stand', 'Stand'), ('Basis', 'Basis')], max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('ОБЩИЕ', 'ОБЩИЕ'), ('age', 'Age Category'), ('rigidity', 'Rigidity level of side'), ('cover', 'Cover'), ('', ''), ('Mattress', 'ТОЛЬКО MATTRESS'), ('mattress_type', 'Mattress Type'), ('collection', 'Collection'), ('construction', 'Construction'), ('rigidity', 'Rigidity level of side'), ('springblock', 'Spring block'), ('', ''), ('Pillow', 'ТОЛЬКО PILLOW'), ('material_filler', 'Material Filler'), ('', ''), ('MattressPad', 'ТОЛЬКО MATTRESS PAD'), ('mattresspad_type', 'Mattress Pad Type'), ('rigidity', 'Rigidity level of side'), ('binding', 'Contour'), ('', ''), ('Blanket', 'ТОЛЬКО BLANKET'), ('blanket_type', 'Blanket Type'), ('blanket_color', 'Blanket Color'), ('filling', 'Filling'), ('', ''), ('Bed', 'ТОЛЬКО BED'), ('bed_type', 'Bed Type'), ('', ''), ('Stand', 'ТОЛЬКО STAND'), ('material', 'Material'), ('', ''), ('Basis', 'ТОЛЬКО BASIS')], max_length=32, verbose_name='Characteristic'),
        )
    ]
