# Generated by Django 4.1.1 on 2023-08-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_bedsheetssize_duvet_cover_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='duvet_cover_size',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='elasticated_sheet_size',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='pillowcase_sizes',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='sheet_size',
        ),
        migrations.RemoveField(
            model_name='bedsheetssize',
            name='size_ptr',
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('COMMON', 'COMMON'), ('age', 'Age Category'), ('rigidity', 'Rigidity level of side'), ('cover', 'Cover'), ('', ''), ('Mattress', 'ONLY MATTRESS'), ('mattress_type', 'Mattress Type'), ('collection', 'Collection'), ('construction', 'Construction'), ('rigidity', 'Rigidity level of side'), ('springblock', 'Spring block'), ('', ''), ('Pillow', 'ONLY PILLOW'), ('material_filler', 'Material Filler'), ('', ''), ('MattressPad', 'ONLY MATTRESS PAD'), ('mattresspad_type', 'Mattress Pad Type'), ('rigidity', 'Rigidity level of side'), ('binding', 'Contour'), ('', ''), ('Blanket', 'ONLY BLANKET'), ('blanket_type', 'Blanket Type'), ('blanket_color', 'Blanket Color'), ('filling', 'Filling'), ('', ''), ('Bed', 'ONLY BED'), ('bed_type', 'Bed Type'), ('', ''), ('Stand', 'ONLY STAND'), ('material', 'Material')], max_length=32, verbose_name='Characteristic'),
        ),
        migrations.DeleteModel(
            name='BedSheets',
        ),
        migrations.DeleteModel(
            name='BedSheetsSize',
        ),
    ]
