# Generated by Django 4.1.1 on 2023-08-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_rename_priceeur_size_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mattress',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_technology',
        ),
        migrations.AlterField(
            model_name='mattress',
            name='structure',
            field=models.ManyToManyField(through='api.LayerMattress', to='api.technology', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='structure',
            field=models.ManyToManyField(through='api.LayerMattressPad', to='api.technology', verbose_name='Структура'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='structure',
            field=models.ManyToManyField(through='api.LayerPillow', to='api.technology', verbose_name='Структура'),
        ),
    ]
