# Generated by Django 4.1.1 on 2023-08-13 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_mattress_technologies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoldingBed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('desc_gr', models.TextField(verbose_name='Description (gr)')),
                ('desc_en', models.TextField(verbose_name='Description (en)')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Discount (%)')),
                ('mattress_height', models.IntegerField(default=0)),
                ('mezanine', models.BooleanField(default=False)),
                ('shelves', models.BooleanField(default=False)),
                ('height', models.IntegerField(default=0)),
                ('max_pressure', models.IntegerField(default=0)),
                ('age', models.ManyToManyField(related_name='age%(class)s', to='api.choice')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base', to='api.choice')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category')),
                ('closed_dimensions', models.ManyToManyField(related_name='closed_dimensions%(class)s', to='api.size', verbose_name='Closed Dimensions')),
                ('images', models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos')),
                ('shortcut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut')),
                ('sizes', models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes')),
                ('table_dimensions', models.ManyToManyField(blank=True, related_name='table_dimensions%(class)s', to='api.size', verbose_name='Table Dimensions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('desc_gr', models.TextField(verbose_name='Description (gr)')),
                ('desc_en', models.TextField(verbose_name='Description (en)')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Discount (%)')),
                ('depth', models.IntegerField(default=0)),
                ('countertop_length', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('countertop_weight', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category')),
                ('images', models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos')),
                ('shortcut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut')),
                ('sizes', models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='basis',
            name='best',
        ),
        migrations.RemoveField(
            model_name='basis',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='best',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='best',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='best',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='best',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='best',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='best',
        ),
        migrations.RemoveField(
            model_name='stand',
            name='videos',
        ),
        migrations.AlterField(
            model_name='basis',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='desc_en',
            field=models.TextField(verbose_name='Description (en)'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='desc_gr',
            field=models.TextField(verbose_name='Description (gr)'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='discount',
            field=models.SmallIntegerField(default=0, verbose_name='Discount (%)'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='shortcut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
