# Generated by Django 4.1.1 on 2023-08-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_foldingbed_table_remove_basis_best_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foldingbed',
            name='mezanine',
        ),
        migrations.RemoveField(
            model_name='foldingbed',
            name='shelves',
        ),
        migrations.RemoveField(
            model_name='size',
            name='on_sale',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FoldingBed', 'Murhy Bed'), ('Bed', 'Bed'), ('Mattress', 'Mattress'), ('Table', 'Table'), ('Pillow', 'Pillow'), ('MattressPad', 'Mattress Pad'), ('Blanket', 'Blanket'), ('Stand', 'Stand'), ('Basis', 'Basis')], max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_pl',
            field=models.CharField(blank=True, max_length=32, verbose_name='English plural'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en_s',
            field=models.CharField(blank=True, max_length=32, verbose_name='English singular'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_gr_pl',
            field=models.CharField(blank=True, max_length=32, verbose_name='Greek plural'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_gr_s',
            field=models.CharField(blank=True, max_length=32, verbose_name='Greek singular'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('COMMON', 'COMMON'), ('age', 'Age Category'), ('rigidity', 'Rigidity level of side'), ('cover', 'Cover'), ('', ''), ('FoldingBed', 'ONLY MURHY BED'), ('base', 'Mattress Base'), ('', ''), ('Bed', 'ONLY BED'), ('bed_type', 'Bed Type'), ('', ''), ('Mattress', 'ONLY MATTRESS'), ('mattress_type', 'Mattress Type'), ('collection', 'Collection'), ('construction', 'Construction'), ('rigidity', 'Rigidity level of side'), ('springblock', 'Spring block'), ('', ''), ('Table', 'ONLY TABLE'), ('', ''), ('Pillow', 'ONLY PILLOW'), ('material_filler', 'Material Filler'), ('', ''), ('MattressPad', 'ONLY MATTRESS PAD'), ('mattresspad_type', 'Mattress Pad Type'), ('rigidity', 'Rigidity level of side'), ('binding', 'Contour'), ('', ''), ('Blanket', 'ONLY BLANKET'), ('blanket_type', 'Blanket Type'), ('blanket_color', 'Blanket Color'), ('filling', 'Filling'), ('', ''), ('Stand', 'ONLY STAND'), ('material', 'Material')], max_length=32, verbose_name='Characteristic'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
