# Generated by Django 4.1.1 on 2023-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_rename_stand_puff_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('total', models.IntegerField(verbose_name='Total')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=32, verbose_name='City')),
                ('phone', models.CharField(max_length=16, verbose_name='Phone')),
                ('address', models.CharField(max_length=128, verbose_name='Address')),
                ('shipping', models.CharField(choices=[('showroom', 'showroom'), ('courier', 'courier')], max_length=8, verbose_name='Shiiping Method')),
                ('sizes', models.ManyToManyField(to='api.size', verbose_name='Picked Sizes')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
