# Generated by Django 4.1.1 on 2023-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordered'),
        ),
    ]
