# Generated by Django 4.1.1 on 2023-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_size_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='Lemasos', max_length=32, verbose_name='City'),
        ),
    ]
