# Generated by Django 4.1.1 on 2023-08-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_order_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='size',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='size',
            name='quantity',
        ),
    ]
