# Generated by Django 4.1.1 on 2023-08-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_order_sizes_remove_size_ordered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order', verbose_name='Order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.size', verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='sizes',
            field=models.ManyToManyField(blank=True, through='api.OrderedSize', to='api.size', verbose_name='Picked Sizes'),
        ),
    ]
