# Generated by Django 4.1.1 on 2023-09-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_orderedsize_order_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='suggestions',
            field=models.ManyToManyField(to='api.basis', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='bed',
            name='suggestions',
            field=models.ManyToManyField(to='api.bed', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='suggestions',
            field=models.ManyToManyField(to='api.blanket', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='foldingbed',
            name='suggestions',
            field=models.ManyToManyField(to='api.foldingbed', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='suggestions',
            field=models.ManyToManyField(to='api.mattress', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='mattresspad',
            name='suggestions',
            field=models.ManyToManyField(to='api.mattresspad', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='suggestions',
            field=models.ManyToManyField(to='api.pillow', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='puff',
            name='suggestions',
            field=models.ManyToManyField(to='api.puff', verbose_name='Suggestions'),
        ),
        migrations.AddField(
            model_name='table',
            name='suggestions',
            field=models.ManyToManyField(to='api.table', verbose_name='Suggestions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('showroom', 'showroom'), ('courier', 'courier')], default='showroom', max_length=8, verbose_name='Shipping Method'),
        ),
    ]
