# Generated by Django 4.1.1 on 2023-09-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_basis_suggestions_bed_suggestions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basis',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='foldingbed',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='puff',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='table',
            name='suggestions',
        ),
        migrations.AddField(
            model_name='basis',
            name='suggestions_bed',
            field=models.ManyToManyField(to='api.bed'),
        ),
        migrations.AddField(
            model_name='basis',
            name='suggestions_mattress',
            field=models.ManyToManyField(to='api.mattress'),
        ),
        migrations.AddField(
            model_name='bed',
            name='suggestions_mattress',
            field=models.ManyToManyField(to='api.mattress'),
        ),
        migrations.AddField(
            model_name='bed',
            name='suggestions_puff',
            field=models.ManyToManyField(to='api.puff'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='suggestions_mattresspad',
            field=models.ManyToManyField(to='api.mattresspad'),
        ),
        migrations.AddField(
            model_name='blanket',
            name='suggestions_pillow',
            field=models.ManyToManyField(to='api.pillow'),
        ),
        migrations.AddField(
            model_name='foldingbed',
            name='suggestions_mattress',
            field=models.ManyToManyField(to='api.mattress'),
        ),
        migrations.AddField(
            model_name='foldingbed',
            name='suggestions_puff',
            field=models.ManyToManyField(to='api.puff'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='suggestions_mattresspad',
            field=models.ManyToManyField(to='api.mattresspad'),
        ),
        migrations.AddField(
            model_name='mattress',
            name='suggestions_pillow',
            field=models.ManyToManyField(to='api.pillow'),
        ),
        migrations.AddField(
            model_name='mattresspad',
            name='suggestions_blanket',
            field=models.ManyToManyField(to='api.blanket'),
        ),
        migrations.AddField(
            model_name='mattresspad',
            name='suggestions_pillow',
            field=models.ManyToManyField(to='api.pillow'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='suggestions_blanket',
            field=models.ManyToManyField(to='api.blanket'),
        ),
        migrations.AddField(
            model_name='pillow',
            name='suggestions_mattresspad',
            field=models.ManyToManyField(to='api.mattresspad'),
        ),
        migrations.AddField(
            model_name='puff',
            name='suggestions_foldingbed',
            field=models.ManyToManyField(to='api.foldingbed'),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('desc_gr', models.TextField(verbose_name='Description (gr)')),
                ('desc_en', models.TextField(verbose_name='Description (en)')),
                ('discount', models.SmallIntegerField(default=0, verbose_name='Discount (%)')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Category')),
                ('images', models.ManyToManyField(blank=True, related_name='images%(class)s', to='api.image', verbose_name='Photos')),
                ('shortcut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image', verbose_name='shortcut')),
                ('sizes', models.ManyToManyField(related_name='sizes%(class)s', to='api.size', verbose_name='Sizes')),
                ('suggestions_accessory', models.ManyToManyField(to='api.accessory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='table',
            name='suggestions_accessory',
            field=models.ManyToManyField(to='api.accessory'),
        ),
    ]
