# Generated by Django 4.1.1 on 2023-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_remove_basis_suggestions_remove_bed_suggestions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blanket',
            old_name='suggestions_mattresspad',
            new_name='suggestions_mattress_pad',
        ),
        migrations.RenameField(
            model_name='mattress',
            old_name='suggestions_mattresspad',
            new_name='suggestions_mattress_pad',
        ),
        migrations.RenameField(
            model_name='pillow',
            old_name='suggestions_mattresspad',
            new_name='suggestions_mattress_pad',
        ),
        migrations.RenameField(
            model_name='puff',
            old_name='suggestions_foldingbed',
            new_name='suggestions_folding_bed',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FoldingBed', 'Murhy Bed'), ('Bed', 'Bed'), ('Mattress', 'Mattress'), ('Table', 'Table'), ('Pillow', 'Pillow'), ('MattressPad', 'Mattress Pad'), ('Blanket', 'Blanket'), ('Basis', 'Basis'), ('Puff', 'Puff'), ('Accessory', 'Accessory')], max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(choices=[('COMMON', 'COMMON'), ('age', 'Age Category'), ('rigidity', 'Rigidity level of side'), ('cover', 'Cover'), ('', ''), ('FoldingBed', 'ONLY MURHY BED'), ('base', 'Mattress Base'), ('', ''), ('Bed', 'ONLY BED'), ('bed_type', 'Bed Type'), ('', ''), ('Mattress', 'ONLY MATTRESS'), ('mattress_type', 'Mattress Type'), ('collection', 'Collection'), ('construction', 'Construction'), ('rigidity', 'Rigidity level of side'), ('springblock', 'Spring block'), ('', ''), ('Table', 'ONLY TABLE'), ('', ''), ('Pillow', 'ONLY PILLOW'), ('material_filler', 'Material Filler'), ('', ''), ('MattressPad', 'ONLY MATTRESS PAD'), ('mattresspad_type', 'Mattress Pad Type'), ('rigidity', 'Rigidity level of side'), ('binding', 'Contour'), ('', ''), ('Blanket', 'ONLY BLANKET'), ('blanket_type', 'Blanket Type'), ('blanket_color', 'Blanket Color'), ('filling', 'Filling'), ('', ''), ('Puff', 'ONLY PUFF'), ('material', 'Material'), ('', ''), ('Accessory', 'ONLY ACCESSORY')], max_length=32, verbose_name='Characteristic'),
        ),
    ]
