# Generated by Django 4.1.1 on 2023-09-05 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_rename_suggestions_mattresspad_blanket_suggestions_mattress_pad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='suggestions_accessory',
        ),
        migrations.RemoveField(
            model_name='basis',
            name='suggestions_bed',
        ),
        migrations.RemoveField(
            model_name='basis',
            name='suggestions_mattress',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='suggestions_mattress',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='suggestions_puff',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='suggestions_mattress_pad',
        ),
        migrations.RemoveField(
            model_name='blanket',
            name='suggestions_pillow',
        ),
        migrations.RemoveField(
            model_name='foldingbed',
            name='suggestions_mattress',
        ),
        migrations.RemoveField(
            model_name='foldingbed',
            name='suggestions_puff',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='suggestions_mattress_pad',
        ),
        migrations.RemoveField(
            model_name='mattress',
            name='suggestions_pillow',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='suggestions_blanket',
        ),
        migrations.RemoveField(
            model_name='mattresspad',
            name='suggestions_pillow',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='suggestions_blanket',
        ),
        migrations.RemoveField(
            model_name='pillow',
            name='suggestions_mattress_pad',
        ),
        migrations.RemoveField(
            model_name='puff',
            name='suggestions_folding_bed',
        ),
        migrations.RemoveField(
            model_name='table',
            name='suggestions_accessory',
        ),
    ]
