# Generated by Django 4.1.1 on 2023-09-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_accessory_suggestions_accessory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='basis',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='blanket',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='foldingbed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='mattress',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='mattresspad',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='pillow',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='puff',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='category',
            new_name='categories',
        ),
    ]
