# Generated by Django 4.1.1 on 2023-09-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_alter_accessory_options_alter_basis_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldingbed',
            name='cushion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cushion', to='api.choice'),
        ),
        migrations.AddField(
            model_name='foldingbed',
            name='lamels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foldingbed',
            name='legs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='api.choice'),
        ),
        migrations.AddField(
            model_name='foldingbed',
            name='wall',
            field=models.ManyToManyField(related_name='wall', to='api.choice'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='suggestions_Accessory',
            field=models.ManyToManyField(blank=True, to='api.accessory'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='suggestions_Bed',
            field=models.ManyToManyField(blank=True, to='api.bed'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='suggestions_Mattress',
            field=models.ManyToManyField(blank=True, to='api.mattress'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='suggestions_Mattress',
            field=models.ManyToManyField(blank=True, to='api.mattress'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='suggestions_Puff',
            field=models.ManyToManyField(blank=True, to='api.puff'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='suggestions_MattressPad',
            field=models.ManyToManyField(blank=True, to='api.mattresspad'),
        ),
        migrations.AlterField(
            model_name='blanket',
            name='suggestions_Pillow',
            field=models.ManyToManyField(blank=True, to='api.pillow'),
        ),
        migrations.AlterField(
            model_name='foldingbed',
            name='suggestions_Mattress',
            field=models.ManyToManyField(blank=True, to='api.mattress'),
        ),
        migrations.AlterField(
            model_name='foldingbed',
            name='suggestions_Puff',
            field=models.ManyToManyField(blank=True, to='api.puff'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='suggestions_MattressPad',
            field=models.ManyToManyField(blank=True, to='api.mattresspad'),
        ),
        migrations.AlterField(
            model_name='mattress',
            name='suggestions_Pillow',
            field=models.ManyToManyField(blank=True, to='api.pillow'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='suggestions_Blanket',
            field=models.ManyToManyField(blank=True, to='api.blanket'),
        ),
        migrations.AlterField(
            model_name='mattresspad',
            name='suggestions_Pillow',
            field=models.ManyToManyField(blank=True, to='api.pillow'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='suggestions_Blanket',
            field=models.ManyToManyField(blank=True, to='api.blanket'),
        ),
        migrations.AlterField(
            model_name='pillow',
            name='suggestions_MattressPad',
            field=models.ManyToManyField(blank=True, to='api.mattresspad'),
        ),
        migrations.AlterField(
            model_name='puff',
            name='suggestions_FoldingBed',
            field=models.ManyToManyField(blank=True, to='api.foldingbed'),
        ),
        migrations.AlterField(
            model_name='table',
            name='suggestions_Accessory',
            field=models.ManyToManyField(blank=True, to='api.accessory'),
        ),
    ]
