# Generated by Django 4.1.1 on 2023-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_remove_table_depth_table_dimensions_table_fixation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='article_en',
            field=models.TextField(blank=True, verbose_name='Article (en)'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='article_gr',
            field=models.TextField(blank=True, verbose_name='Article (gr)'),
        ),
        migrations.AlterField(
            model_name='foldingbed',
            name='article_en',
            field=models.TextField(blank=True, verbose_name='Article (en)'),
        ),
        migrations.AlterField(
            model_name='foldingbed',
            name='article_gr',
            field=models.TextField(blank=True, verbose_name='Article (gr)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='article_en',
            field=models.TextField(blank=True, verbose_name='Article (en)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='article_gr',
            field=models.TextField(blank=True, verbose_name='Article (gr)'),
        ),
    ]
