from .folding_bed import FoldingBedSerializer
from .bed import BedSerializer
from .mattress import MattressSerializer
from .table import TableSerializer
from .pillow import PillowSerializer
from .mattress_pad import MattressPadSerializer
from .blanket import BlanketSerializer
from .accessory import AccessorySerializer
from .basis import BasisSerializer
from .puff import PuffSerializer