from .folding_bed import FoldingBedManager
from .bed import BedManager
from .mattress import MattressManager
from .table import TableManager
from .pillow import PillowManager
from .mattress_pad import MattressPadManager
from .blanket import BlanketManager
from .accessory import AccessoryManager
from .basis import BasisManager
from .puff import PuffManager