from .folding_bed import FoldingBed
from .bed import Bed
from .mattress import Mattress
from .table import Table
from .pillow import Pillow
from .mattress_pad import MattressPad
from .blanket import Blanket
from .accessory import Accessory
from .basis import Basis
from .puff import Puff